// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxEDOBgyygMDubLEjkw_Ddl12HulTkM8',
    appId: '1:238531004197:web:cc74c1f0608f6aa5d9fccc',
    messagingSenderId: '238531004197',
    projectId: 'e-commerce-b3875',
    authDomain: 'e-commerce-b3875.firebaseapp.com',
    storageBucket: 'e-commerce-b3875.firebasestorage.app',
    measurementId: 'G-LRR8NQ7RDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4EN_M8YaqzwZRyQ8K1f7DE-YhvZee-mQ',
    appId: '1:238531004197:android:dc6dbc17789f2e24d9fccc',
    messagingSenderId: '238531004197',
    projectId: 'e-commerce-b3875',
    storageBucket: 'e-commerce-b3875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjKIr6tE_Kpnsl5Q522IbPO4rOVe_7AsE',
    appId: '1:238531004197:ios:6e44f255465879f5d9fccc',
    messagingSenderId: '238531004197',
    projectId: 'e-commerce-b3875',
    storageBucket: 'e-commerce-b3875.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjKIr6tE_Kpnsl5Q522IbPO4rOVe_7AsE',
    appId: '1:238531004197:ios:6e44f255465879f5d9fccc',
    messagingSenderId: '238531004197',
    projectId: 'e-commerce-b3875',
    storageBucket: 'e-commerce-b3875.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZxEDOBgyygMDubLEjkw_Ddl12HulTkM8',
    appId: '1:238531004197:web:2b605aa5aad7abf9d9fccc',
    messagingSenderId: '238531004197',
    projectId: 'e-commerce-b3875',
    authDomain: 'e-commerce-b3875.firebaseapp.com',
    storageBucket: 'e-commerce-b3875.firebasestorage.app',
    measurementId: 'G-TBYCCLDZXS',
  );
}
